### ISSUE TITLE
More stats

### ISSUE THREAD

**Issue by Devilman12345** [kcaf/PokeRadar#1]
I was wondering if you could extend the stats feature to show ivs and ability for wild pokemons, and also a search setting that searches for pokemon that are in the area that has a hidden ability, Thanks for this awesome mod!

**Comment by kcaf** [comment]
We're actually limited at the moment when it comes to wild pokemon. Those stats are only known on the server until you decide to battle or capture the pokemon. I'm looking at ways to bypass this, but nothing has worked to date. Thank you for the kind words =)

**Comment by Devilman12345** [comment]
Alright, thanks for the reply kcaf! Another suggestion that came to my mind is if there's an easier to search for pokemons that you want. There's a limit to how much you can search at once, unlike on the gameshark mod where you can select and deselect the ones you don't want. Anyways, my appreciation to this mod :)

**Comment by kcaf** [comment]
Great idea!
I can definitely do that. I set the original limit to 32 characters back in 2014 when we released this mod. I should have changed it, but I guess I never got around to doing it. I'll update the limit to 255 characters for you :)
