### ISSUE TITLE
One crucial feature missing

### ISSUE THREAD

**Issue by MetalicoMetal** [kcaf/PokeRadar#10]
First of all I will like to say that this mod is awesome, especially the option were you can make it so the dots are replaced by the sprites, that is awesome. But theres one thing that it has missing, i dont know if this can be done but it would be amazing if it could search for abilities or just tell you if an hidden abillity pokemon has spawned like legendarys, not sure if this is imposible but anyways great job on this mod.

**Comment by kcaf** [comment]
Thanks so much! I'm glad you're enjoying the mod! Unfortunately, this isn't possible at the moment. Key information like Hidden Ability are not sent from the server until you either fight the pokemon or own it.
