### ISSUE TITLE
Right click on Pokemon

### ISSUE THREAD

**Issue by yooka102** [kcaf/PokeRadar#14]
Is it possible to display more information? Np ivs %

**Comment by kcaf** [comment]
Unfortunately not. That data appears to be on the server until you own or fight that pokemon.

**Comment by Nomi98** [comment]
Can you add that functionality to battlee mode then? somehow add a switch in the status restore tab?

**Comment by kcaf** [comment]
@Nomi98 I've considered that in the past, but I think for the time being I'm going to keep out of battles. After all, the main function of this mod is to be a radar.

**Comment by Nomi98** [comment]
@kcaf thank you for being awesome and developing this mod man! I can't thank you enough. It makes me sad to see you have discontinued this  mod, and I'll miss it as much as I'll miss Pixelmon. While I want you to have fun and do what you want, a part of me wants you to not quit the project as a whole. However, it's all upto you. Thank you for PokeRadar, :).
