### ISSUE TITLE
IMPORTANT NOTICE

### ISSUE THREAD

**Issue by kcaf** [kcaf/PokeRadar#16]
# Pixelmon development has been discontinued. As such, I will no longer be developing PokeRadar. I have uploaded the source code should you wish to modify it any further. So long, and thanks for all the fish!

[It's been fun everybody!](https://www.youtube.com/watch?v=ehddGxlPGmY) Here's some stats to enjoy.

![Active Sessions](https://i.imgur.com/MsRuPOE.png)
![Total](https://i.imgur.com/5v5uKHI.png)

**Comment by Nomi98** [comment]
But why tho? Will you never update it? Pretty please?

**Comment by metropunisher** [comment]
they are updating it to 5.1.3, its under new development so can you please keep this mod going

**Comment by kcaf** [comment]
@metropunisher who is **they** in this context? The official mod seems to be dead now.

**Comment by metropunisher** [comment]
A group called SkullPacks heres the link to the new pixelmon https://www.technicpack.net/modpack/pixelmon-advancedtm.1067680

**Comment by kcaf** [comment]
@metropunisher Didn't take very long for that to die. The problem with this moving forward is the more underground it goes, the less scrupulous the developers you will find willing to continue the project. It's only a small offset from a malicious author picking up the code for a few days just to get quick downloads on their malware.

The existing version of Pixelmon works with my code. Should you come across a version that does not, and are willing to risk running that mystery code, I have provided my source for you to alter for yourself. It's been a fun ride gents since the beginning of PokeRadar so very long ago. Thank you all so much.

**Comment by Nomi98** [comment]
Didn't really die, they just changed the name; https://www.technicpack.net/modpack/tmpixelmon-darktm.1078342/

**Comment by Dimenti099** [comment]
Can confirm it currently works with Pixelmon Dark as-is.

**Comment by kcaf** [comment]
See Issue #29
