### ISSUE TITLE
Detected by Pixelmon Dark?

### ISSUE THREAD

**Issue by Blue-Mew** [kcaf/PokeRadar#21]
I tried to join a server but it gave me a 'This server does not allow PokeRadar' on Pixelmon Dark 1.7.

**Comment by Deltanium** [comment]
If you read the post, it's no longer being supported, and if it is blocked just try changing the mod description and name, that gets around the mod blockers for the most part.

**Comment by darkrailove** [comment]
i am having the same problem and try doing that but it still said that maybe i am doing it wrong do you think you do it for me ?

**Comment by Deltanium** [comment]
You change it via a .json file within the mod. If you can't do that you shouldn't be using this anyway

**Comment by darkrailove** [comment]
have you acculay done this
where is the .json file located

**Comment by darkrailove** [comment]
all i can find is a mcmod.info

**Comment by darkrailove** [comment]
and know changing the data in that doesnt work

**Comment by Blue-Mew** [comment]
Ok, can change the Mod ID and description, but which tool to rebuild it?

**Comment by kcaf** [comment]
I've made a decision to continue supporting PokeRadar for the time being and will address this. See Issue #29

**Comment by kcaf** [comment]
@Blue-Mew @Deltanium @darkrailov
Could one of you give me info for a server that is blocking your PokeRadar? I'd like to test workarounds.

**Comment by kcaf** [comment]
I'm closing this issue as I believe it is resolved now. If anyone reading this can show me a server that is currently detecting pokeradar, please open a new issue and provide the relevant information.
