### ISSUE TITLE
Read before submitting issues:

### ISSUE THREAD

**Issue by Deltanium** [kcaf/PokeRadar#22]
Read through the past issues, if your isn't fixed, increase your ram, switch to forge if you're technically, and delete the .cfg, if it's blocked by servers, change mod info and change the description and name, not the file name, the mod name, Google if you need further help

**Comment by root-kali** [comment]
I was wondering if you could help.
I tried everything you said and it still detects.

**Comment by root-kali** [comment]
also if u have discord i might be able to make you some money $$ :)
