### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by rainbowmango03** [kcaf/PokeRadar#23]
so I keep on try to play and it shows this message

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PokeRadar (pokeradar)

**Comment by kcaf** [comment]
If this problem persists with the latest version of pokeradar (make sure you're updated), then open a new issue and post the full crash report file.
