### ISSUE TITLE
Interaction with Pixelmon Dark/Generations

### ISSUE THREAD

**Issue by SwingBlade** [kcaf/PokeRadar#26]
Hi there!

I see that this does detect and display all the new Dark pokemon, but I was wondering if it had proper alerts for the new legendaries and mega bosses, or if they'll also simply display as white dots? Is there a way that the legendary/mega boss list could be updated clientside to include all the additions? Similarly, will new shiny pokemon show as such on the map? Thanks!

**Comment by kcaf** [comment]
I've made a decision to continue supporting PokeRadar for the time being and will address this. See Issue #29
