### ISSUE TITLE
Pokeradar Black blotches

### ISSUE THREAD

**Issue by Deadbeatkids** [kcaf/PokeRadar#33]
Black blotches have appeared over the map, 
Why are they there?
![unknown](https://user-images.githubusercontent.com/36643136/36392443-15bc3ba0-15a3-11e8-8a90-82ab66cbd924.png)

**Comment by kcaf** [comment]
This can happen sometimes if the map becomes corrupted. Follow these steps to fix it https://github.com/kcaf/PokeRadar/wiki/Reset-corrupted-map
