### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Teletubiesguy** [kcaf/PokeRadar#35]
Dear kcaf ,
I have got some suggestions for your mod, but first of all I want to thank you for this incredible mod 
Here are my suggestions :
1) I was going for checking ivs and abilities of wild pokes but I saw that it's impossible in another message,
so why would you not add a growth thing, we could use it to seek pokemons with specific growths such as Enormous,Pigmy...
2) Is it possible for you to make an option to seek Hidden Ability pokemons, if you can that would be really useful
3) Is it possible for you to show what EVS do give wild pokemons (Precise evs like Gengar you would write 3 SPATK), like on top of its name
Anyway I hope that you could add these, Peace.

**Comment by kcaf** [comment]
Hey there, thanks for the feedback!
1. I was going for checking ivs and abilities of wild pokes but I saw that it's impossible in another message,
so why would you not add a growth thing, we could use it to seek pokemons with specific growths such as Enormous,Pigmy...
**It's something I could do, but I never saw the mass benefit to it and too many options would add clutter. If feedback is strong for this feature, I'll add it in.

2. Is it possible for you to make an option to seek Hidden Ability pokemons, if you can that would be really useful
**Sorry this is not possible**

3. Is it possible for you to show what EVS do give wild pokemons (Precise evs like Gengar you would write 3 SPATK), like on top of its name
Anyway I hope that you could add these, Peace.
**This is definitely possible, but I believe it's already covered by the EV Filter. I could change it up so if the EV filter is on, it would display the precise EV above the name. That's a good idea.**

**Comment by Teletubiesguy** [comment]
Okay ^^, thanks for answering :)
