### ISSUE TITLE
Other Suggestions ^^

### ISSUE THREAD

**Issue by Teletubiesguy** [kcaf/PokeRadar#36]
Hello again ,
I've got other suggestions that I've forgot to tell you :

 1) Is there any way for you to allow us to see other player teams ? That would be a cool feature ^^
 2) And the second one is to Locate specific biomes that are near us such as a Savanna Plateau M if we are 
     in a savanna plateau and other biomes
 3) This would be a really cool feature if you could add like something that shows us where EVERY 
     Legendaries/Pokemons spawn

**Comment by kcaf** [comment]
1. Is there any way for you to allow us to see other player teams ? That would be a cool feature ^^
**I'll consider adding support for this in the future, but it's a bit out of scope for "radar"**

2. And the second one is to Locate specific biomes that are near us such as a Savanna Plateau M if we are in a savanna plateau and other biomes
**This would have to do with the specific seed of the server. I'm sure tools exist to reverse engineer the biomes from the seed, but I'm not going to do that**

3. This would be a really cool feature if you could add like something that shows us where EVERY
Legendaries/Pokemons spawn
**I believe this information is available on the pixelmon wiki**
