### ISSUE TITLE
Minecraft crashes when I enable use textures

### ISSUE THREAD

**Issue by MrDemocracy** [kcaf/PokeRadar#38]
When I enable the use textures, minecraft crashes after exiting the menu. I'm not able to start minecraft again unless I delete the config file.

**Comment by kcaf** [comment]
I can't help you without a crash log. Can you please provide one?

**Comment by MrDemocracy** [comment]
Managed to solve it by updating pixelmon.

However now that I managed to load the icons without minecraft crashing, I noticed that there still where no pokemon on the map. After further investigation I found out that it's because the map loads from dimension 0 but the mob icons are only visible if I change the dimension to 11. 
Is there a way to fix this? And do you still want my minecraft logs even after the crash is resolved?
