### ISSUE TITLE
Map is showing Leaves, Water, Sand and other as solid black

### ISSUE THREAD

**Issue by BobOrSomething** [kcaf/PokeRadar#4]
So I'm not sure what all started this it just kind of happened out of no where things like Leaves, Water, Sand and certain altitudes are just solid black on the map and snow doesn't even seem to show up. Every now and then it decides it wants to work then usually after I crash it's broken again. (The crashing alone is a horribly annoying problem and I have no idea how to fix it but that's a separate thing all together)

Only mods I have installed is Pixelmon, Pokeradar, Optifine, InvTweaks, and Waila not sure if that combination is doing anything but that's it. I've also tried uninstalling and reinstalling not sure what happened.

Having a resource pack on or off doesn't seem to change anything either.

Here's an image I took from the large map
![image](https://cloud.githubusercontent.com/assets/29085314/26616215/ee36d03c-459a-11e7-986a-0af484a1fd7a.png)

**Comment by kcaf** [comment]
I've heard this bug multiple times now to warrant investigation. However, I believe this to be a bug with Mapwriter itself (the open source software Pokeradar is based upon). Because of that, I can't promise a resolution, but I will certainly look into it.

**Comment by BobOrSomething** [comment]
I appreciate the response and I wish you good luck on figuring it all out!
