### ISSUE TITLE
Map in like an x-ray mode

### ISSUE THREAD

**Issue by sjkunder** [kcaf/PokeRadar#40]
up graded to 1.12 for Pixelmon and now my map shows lava rivers , water and land and not much else.  Also it there a way to bring over may saved data from the earlier version to this version?

![image](https://user-images.githubusercontent.com/37976293/38172526-41fb7c46-35e0-11e8-921e-5355421b2b97.png)

**Comment by kcaf** [comment]
Did the server upgrade? It's probably changed the landscape by porting over. Nothing can be done when servers do this except to reset your map.
https://github.com/kcaf/PokeRadar/wiki/Reset-corrupted-map

**Comment by Leapinlightning** [comment]
I'm having this exact issue too, my map looks just like that. The server I'm playing on did just upgrade but the map was reset anyways. I followed the steps in the Reset Corrupted Map page and the problem persisted. Is there anything else I can try?

**Comment by sjkunder** [comment]
Got it up and working Not sure witch fixed it as I for got to move around on the map before moving on to FoamFix ....any there I have not been back to still looks broke
