### ISSUE TITLE
Hotkey 'N' overrides TCG mod crafting menu

### ISSUE THREAD

**Issue by pigneedle** [kcaf/PokeRadar#44]
Pressing 'N' with Pixelmon Radar installed prevents the user from opening the TCG mod crafting menu which uses the same hotkey.

**Comment by kcaf** [comment]
That is hotkey that carried over from the map plugin I used. I believe there is a setting somewhere to change the activation key, but you'll have to fish around for it.

**Comment by pigneedle** [comment]
I found it. This is a non-issue and can be closed.

**Comment by kcaf** [comment]
Awesome. Would you kindly post how its done for future seekers?

**Comment by pigneedle** [comment]
Options>Controls

 

Hotkeys can be changed from there.

**Comment by kcaf** [comment]
Many thanks. Closing the issue now.
