### ISSUE TITLE
Lines in Pokeradar

### ISSUE THREAD

**Issue by bencam112** [kcaf/PokeRadar#45]
Hi there.
I have a problem with the lines in the Pokeradar for pixelmon version 5. I have pixelmon version 6.2.3 and for some reason when i add the pokeradar to my pixelmon it does not have any lines to show me where the pokemon are, and there are no coloured dots, only white dots for the pokemon

**Comment by kcaf** [comment]
You can enable the lines in the config. They are not enabled by default. Try creating a single player server with cheats enabled and spawn a shiny. Let me know if that works.

**Comment by bencam112** [comment]
It’s fine thanks I got to work!
