### ISSUE TITLE
Unable to load menu

### ISSUE THREAD

**Issue by Suiterkee** [kcaf/PokeRadar#46]
I'm not getting any type of error however there is no way for me to pull up the menu for the mod. I do have the map on the top right and it highlights poke-loot but nothing more. I've tried re-downloading it several times. My friend however is able to use the \ key and load the menu fine. I'm at a loss for what to do.

**Comment by kcaf** [comment]
You might be able to change the hotkey in the Options > Controls menu

**Comment by kcaf** [comment]
Try to figure out which mod is conflicting with it and see if you can alter that mod.

**Comment by Deltanium** [comment]
List of mods that you are using? If i had to suggestion, slowly remove a
mod per load up, If the issue goes away, the last mod that was removed was
causing the issue
