### ISSUE TITLE
No longer works for new pixelmon update

### ISSUE THREAD

**Issue by Blackbunny0159** [kcaf/PokeRadar#48]
They updated pixelmon and now specifically detect pokeradar and instantly kick you from the server 
please tell me theres an update on the way

**Comment by adolfs11** [comment]
Are you using pixelmon reforged? I assume so, because it got an update last night, but from my experience, I don't get kicked, but my game simply crashes.

**Comment by Blackbunny0159** [comment]
No i am 100% server are now detecting pokeradar


________________________________

**Comment by Blackbunny0159** [comment]
Hopefully im wrong
i love your mod 😊

________________________________

**Comment by kcaf** [comment]
The servers are not detecting it. There's just a null reference. Relax. I'll get to it when I can.

**Comment by kcaf** [comment]
Update to version 4.3
