### ISSUE TITLE
Pokemon Tracer and Hidden Ability Filter.

### ISSUE THREAD

**Issue by Milanista999** [kcaf/PokeRadar#5]
Hello, 

I want to start this off by saying that you are doing an amazing job and I love this mod, thank you so much for developing it.

I've got a few of suggestions:

The first one is to add some kind of way to trace the pokemon by having lines that go from the player to the pokemon you're searching for, something similar to this: http://i.imgur.com/pPAmue1.jpg (Pic taken from the GameShark mod)
I'm not sure how hard is it to develop but it could make things easier. Sometimes I find it hard to find the pokemon I'm searching for even with the Waypoints on.

The second idea/suggestion is a little bit more complex but it would be so useful.
I would love to see a Hidden Ability filter added into the mod.
By that I mean having a minimap filter that is going to show you only the Hidden Ability pokemons on the map.
It could use the same filter you're using for the EV/Nature but instead of filtering those you could use it to filter the Hidden Abilities which is going to make finding them a lot easier!

My last suggestion is really simple.
It could be nice if, when you're searching for a pokemon, the minimap was going to show you only the pokemon you're searching for instead of showing every pokemon available..

So, if I'm searching for a Slowbro, the minimap would only show me where are the Slowbros instead of showing me every pokemon.

Hopefully my suggestions are clear enough.
As you might be able to tell, english isn't my first language..

Thank you again!

**Comment by kcaf** [comment]
1.) Line tracing.
It's definitely possible and easy enough to accomplish, but it's probably going to sit on the back burner for a while.

2.) Hidden Ability filter
Not possible at the moment. Certain pokemon data is not known until you complete specific actions with them: battle, capture, view stats. This is one of those things we have no way of knowing when it comes to pokemon in the wild until you physically come in contact with them via one of the aforementioned actions.

3.) Show only searched pokemon
This is a really simple boolean, I'll add that to the feature list for the next version. Thanks!

**Comment by Nomi98** [comment]
May I stress that line tracing is kinda great!

(Thanks for working so hard!)
