### ISSUE TITLE
PokéRadar odd biome colours

### ISSUE THREAD

**Issue by ognickname** [kcaf/PokeRadar#50]
I've been using poke radar for about a week without issue now but all of the sudden certain blocks on the mini map are showing up as incorrect colours. for example birch tree leaves appear yellow and red wool / concrete appears pink. any help to fix this issue would be appreciated.

![image](https://user-images.githubusercontent.com/40307006/41491424-ee8a6aee-70f0-11e8-851c-f170048b7f06.png)

**Comment by kcaf** [comment]
See if this fixes it. https://github.com/kcaf/PokeRadar/wiki/Reset-corrupted-map
