### ISSUE TITLE
please update for 5.1.2

### ISSUE THREAD

**Issue by nvannarsdall** [kcaf/PokeRadar#8]
not necessary but it would be nice to see this on 5.1.2 so i could use it on my favorite server

**Comment by Dimenti099** [comment]
If I recall correctly, it worked with 5.1.1 just fine, so it should still work with 5.1.2

**Comment by kcaf** [comment]
Does it not work with 5.1.2? Please double check and get back to me.

**Comment by Milanista999** [comment]
I'm using it in 5.1.2 and it works perfectly.
